language:           objective-c
os:                 osx
osx_image:          xcode10

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

install:
  - mkdir ~/dataset/
  - git clone https://github.com/Wild-Fang/dataset ~/dataset/
  - ls ~/dataset/

script:
  - chmod +x Trainer.swift
  - ./Trainer.swift

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "YOUR GIT USER NAME"
      - git config --local user.email "YOUR GIT USER EMAIL"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider:     releases
  api_key:      $GITHUB_TOKEN
  file:         "~/AnimalClassifier.mlmodel"
  skip_cleanup: true

notifications:
  email:            false
