language: objective-c
os: osx
osx_image: xcode10

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

install:
  - mkdir ~/dataset/
  - git clone https://github.com/Wild-Fang/dataset ~/dataset/
  - ls ~/dataset/

script:
  - chmod +x Trainer.swift
  - ./Trainer.swift

notifications:
  email:             false
